/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, email: {
                    name: "email",
                    type: "String",
                }, password: {
                    name: "password",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                    isOptional: true,
                }, role: {
                    name: "role",
                    type: "Role",
                    attributes: [{ "name": "@default", "args": [] }],
                }, devices: {
                    name: "devices",
                    type: "Device",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, ownedDashboards: {
                    name: "ownedDashboards",
                    type: "Dashboard",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'owner',
                }, sharedDashboards: {
                    name: "sharedDashboards",
                    type: "Dashboard",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'sharedWith',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            }
            ,
        }
        ,
        deviceType: {
            name: 'DeviceType', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, devices: {
                    name: "devices",
                    type: "Device",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'deviceType',
                }, topicSuffixes: {
                    name: "topicSuffixes",
                    type: "TopicSuffix",
                    isArray: true,
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                },
            }
            ,
        }
        ,
        device: {
            name: 'Device', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "DeviceStatus",
                    attributes: [{ "name": "@default", "args": [] }],
                }, metadata: {
                    name: "metadata",
                    type: "Json",
                    isOptional: true,
                }, deviceType: {
                    name: "deviceType",
                    type: "DeviceType",
                    isDataModel: true,
                    backLink: 'devices',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "deviceTypeId" },
                }, deviceTypeId: {
                    name: "deviceTypeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'deviceType',
                }, userId: {
                    name: "userId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'user',
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'devices',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, locationId: {
                    name: "locationId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'location',
                }, location: {
                    name: "location",
                    type: "Location",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'devices',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "locationId" },
                }, baseTopic: {
                    name: "baseTopic",
                    type: "String",
                }, telemetry: {
                    name: "telemetry",
                    type: "Telemetry",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'device',
                }, alerts: {
                    name: "alerts",
                    type: "Alert",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'device',
                }, dashboards: {
                    name: "dashboards",
                    type: "DashboardDevice",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'device',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, baseTopic: {
                    name: "baseTopic",
                    fields: ["baseTopic"]
                },
            }
            ,
        }
        ,
        location: {
            name: 'Location', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, address: {
                    name: "address",
                    type: "String",
                    isOptional: true,
                }, devices: {
                    name: "devices",
                    type: "Device",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'location',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        telemetry: {
            name: 'Telemetry', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, receivedAt: {
                    name: "receivedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, data: {
                    name: "data",
                    type: "Json",
                }, topicSuffix: {
                    name: "topicSuffix",
                    type: "TopicSuffix",
                }, device: {
                    name: "device",
                    type: "Device",
                    isDataModel: true,
                    backLink: 'telemetry',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "deviceId" },
                }, deviceId: {
                    name: "deviceId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'device',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        alert: {
            name: 'Alert', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, deviceId: {
                    name: "deviceId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'device',
                }, device: {
                    name: "device",
                    type: "Device",
                    isDataModel: true,
                    backLink: 'alerts',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "deviceId" },
                }, severity: {
                    name: "severity",
                    type: "String",
                }, message: {
                    name: "message",
                    type: "String",
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        dashboard: {
            name: 'Dashboard', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, isPublic: {
                    name: "isPublic",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "value": false }] }],
                }, owner: {
                    name: "owner",
                    type: "User",
                    isDataModel: true,
                    backLink: 'ownedDashboards',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "ownerId" },
                }, ownerId: {
                    name: "ownerId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'owner',
                }, sharedWith: {
                    name: "sharedWith",
                    type: "User",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'sharedDashboards',
                }, devices: {
                    name: "devices",
                    type: "DashboardDevice",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'dashboard',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        dashboardDevice: {
            name: 'DashboardDevice', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, dashboard: {
                    name: "dashboard",
                    type: "Dashboard",
                    isDataModel: true,
                    backLink: 'devices',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "dashboardId" },
                }, dashboardId: {
                    name: "dashboardId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'dashboard',
                }, device: {
                    name: "device",
                    type: "Device",
                    isDataModel: true,
                    backLink: 'dashboards',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "deviceId" },
                }, deviceId: {
                    name: "deviceId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'device',
                }, layout: {
                    name: "layout",
                    type: "DashboardDeviceLayout",
                    isTypeDef: true,
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, dashboardId_deviceId: {
                    name: "dashboardId_deviceId",
                    fields: ["dashboardId", "deviceId"]
                },
            }
            ,
        }
        ,
    }
    ,
    typeDefs: {
        dashboardDeviceLayout: {
            name: 'DashboardDeviceLayout', fields: {
                width: {
                    name: "width",
                    type: "WidgetSize",
                }, height: {
                    name: "height",
                    type: "WidgetSize",
                }, order: {
                    name: "order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "value": 0 }] }],
                },
            }
            ,
        }
        ,
    }
    ,
    deleteCascade: {
        device: ['Telemetry', 'Alert', 'DashboardDevice'],
        dashboard: ['DashboardDevice'],
    }
    ,
    authModel: 'User'
};
export default metadata;
